export const ROI_CONFIGS = [
    // ===================== 1 BHK =====================
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "1 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 90,
        cpql: 180,
        cpsv: 900,
        cpb: 18000,
    },
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "1 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 60,
        cpql: 120,
        cpsv: 600,
        cpb: 12000,
    },

    // ===================== 2 BHK =====================
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "2 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 140,
        cpql: 311,
        cpsv: 1400,
        cpb: 28000,
    },
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "2 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 100,
        cpql: 222,
        cpsv: 1000,
        cpb: 20000,
    },

    // ===================== 3 BHK =====================
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 250,
        cpql: 555,
        cpsv: 2500,
        cpb: 50000,
    },
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 200,
        cpql: 445,
        cpsv: 2000,
        cpb: 40000,
    },

    // ===================== 4 BHK =====================
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000,
    },
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000,
    },

    // ===================== 5 BHK =====================
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 1000,
        cpql: 5000,
        cpsv: 25000,
        cpb: 750000,
    },
    {
        segment: "Residential",
        location: "West Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000,
    },
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "1 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 80,
        cpql: 160,
        cpsv: 800,
        cpb: 16000
    },
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "1 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 50,
        cpql: 100,
        cpsv: 500,
        cpb: 10000
    },

    // ---------- 2 BHK ----------
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "2 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 140,
        cpql: 311,
        cpsv: 1400,
        cpb: 28000
    },
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "2 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 100,
        cpql: 222,
        cpsv: 1000,
        cpb: 20000
    },

    // ---------- 3 BHK ----------
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 250,
        cpql: 555,
        cpsv: 2500,
        cpb: 50000
    },
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 200,
        cpql: 445,
        cpsv: 2000,
        cpb: 40000
    },

    // ---------- 4 BHK ----------
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000
    },
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000
    },

    // ---------- 5 BHK ----------
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 900,
        cpql: 4500,
        cpsv: 22500,
        cpb: 675000
    },
    {
        segment: "Residential",
        location: "East Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 750,
        cpql: 3750,
        cpsv: 18750,
        cpb: 562500
    },
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "1 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 100,
        cpql: 200,
        cpsv: 1000,
        cpb: 20000
    },
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "1 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 75,
        cpql: 150,
        cpsv: 750,
        cpb: 15000
    },

    // ---------- 2 BHK ----------
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "2 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 150,
        cpql: 333,
        cpsv: 1500,
        cpb: 30000
    },
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "2 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 125,
        cpql: 278,
        cpsv: 1250,
        cpb: 25000
    },

    // ---------- 3 BHK ----------
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 275,
        cpql: 611,
        cpsv: 2750,
        cpb: 55000
    },
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 225,
        cpql: 500,
        cpsv: 2250,
        cpb: 45000
    },

    // ---------- 4 BHK ----------
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000
    },
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000
    },

    // ---------- 5 BHK ----------
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 900,
        cpql: 4500,
        cpsv: 22500,
        cpb: 675000
    },
    {
        segment: "Residential",
        location: "Central Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 750,
        cpql: 3750,
        cpsv: 18750,
        cpb: 562500
    },
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "1 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 80,
        cpql: 160,
        cpsv: 800,
        cpb: 16000
    },
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "1 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 50,
        cpql: 100,
        cpsv: 500,
        cpb: 10000
    },

    // ---------- 2 BHK ----------
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "2 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 140,
        cpql: 311,
        cpsv: 1400,
        cpb: 28000
    },
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "2 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 100,
        cpql: 222,
        cpsv: 1000,
        cpb: 20000
    },

    // ---------- 3 BHK ----------
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 275,
        cpql: 611,
        cpsv: 2750,
        cpb: 55000
    },
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 225,
        cpql: 500,
        cpsv: 2250,
        cpb: 45000
    },

    // ---------- 4 BHK ----------
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000
    },
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000
    },

    // ---------- 5 BHK ----------
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000
    },
    {
        segment: "Residential",
        location: "Gandhinagar",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 750,
        cpql: 3750,
        cpsv: 18750,
        cpb: 562500
    },
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "1 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 80,
        cpql: 160,
        cpsv: 800,
        cpb: 16000
    },
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "1 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 50,
        cpql: 100,
        cpsv: 500,
        cpb: 10000
    },

    // ---------- 2 BHK ----------
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "2 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 140,
        cpql: 311,
        cpsv: 1400,
        cpb: 28000
    },
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "2 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 100,
        cpql: 222,
        cpsv: 1000,
        cpb: 20000
    },

    // ---------- 3 BHK ----------
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000
    },
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000
    },

    // ---------- 4 BHK ----------
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000
    },
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 750,
        cpql: 3750,
        cpsv: 18750,
        cpb: 562500
    },

    // ---------- 5 BHK ----------
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 1000,
        cpql: 5000,
        cpsv: 25000,
        cpb: 750000
    },
    {
        segment: "Residential",
        location: "West Vadodara",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000
    },
    // ---------- 1 BHK ----------
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "1 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 80,
        cpql: 160,
        cpsv: 800,
        cpb: 16000
    },
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "1 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 50,
        cpql: 100,
        cpsv: 500,
        cpb: 10000
    },

    // ---------- 2 BHK ----------
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "2 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 140,
        cpql: 311,
        cpsv: 1400,
        cpb: 28000
    },
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "2 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 100,
        cpql: 222,
        cpsv: 1000,
        cpb: 20000
    },

    // ---------- 3 BHK ----------
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000
    },
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000
    },

    // ---------- 4 BHK ----------
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000
    },
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 750,
        cpql: 3750,
        cpsv: 18750,
        cpb: 562500
    },

    // ---------- 5 BHK ----------
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 1000,
        cpql: 5000,
        cpsv: 25000,
        cpb: 750000
    },
    {
        segment: "Residential",
        location: "East Vadodara",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000
    }
    ,
    // ---------- OFFICE ----------
    {
        segment: "Commercial",
        location: "West Ahmedabad",
        propertyType: "Office",
        adType: "Static Banner",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 250,
        cpql: 625,
        cpsv: 5000,
        cpb: 125000
    },
    {
        segment: "Commercial",
        location: "West Ahmedabad",
        propertyType: "Office",
        adType: "Static Banner + Reels",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 200,
        cpql: 500,
        cpsv: 4000,
        cpb: 100000
    },

    // ---------- SHOP ----------
    {
        segment: "Commercial",
        location: "West Ahmedabad",
        propertyType: "Shop",
        adType: "Static Banner",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1250,
        cpsv: 8750,
        cpb: 175000
    },
    {
        segment: "Commercial",
        location: "West Ahmedabad",
        propertyType: "Shop",
        adType: "Static Banner + Reels",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 450,
        cpql: 1125,
        cpsv: 7875,
        cpb: 157500
    },

    // ---------- SHOWROOM ----------
    {
        segment: "Commercial",
        location: "West Ahmedabad",
        propertyType: "Showroom",
        adType: "Static Banner",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1400,
        cpql: 4278,
        cpsv: 19250,
        cpb: 385000
    },
    {
        segment: "Commercial",
        location: "West Ahmedabad",
        propertyType: "Showroom",
        adType: "Static Banner + Reels",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1250,
        cpql: 3820,
        cpsv: 17188,
        cpb: 343750
    },
    // ---------- OFFICE ----------
    {
        segment: "Commercial",
        location: "East Ahmedabad",
        propertyType: "Office",
        adType: "Static Banner",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 250,
        cpql: 625,
        cpsv: 5000,
        cpb: 125000
    },
    {
        segment: "Commercial",
        location: "East Ahmedabad",
        propertyType: "Office",
        adType: "Static Banner + Reels",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 200,
        cpql: 500,
        cpsv: 4000,
        cpb: 100000
    },

    // ---------- SHOP ----------
    {
        segment: "Commercial",
        location: "East Ahmedabad",
        propertyType: "Shop",
        adType: "Static Banner",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1250,
        cpsv: 8750,
        cpb: 175000
    },
    {
        segment: "Commercial",
        location: "East Ahmedabad",
        propertyType: "Shop",
        adType: "Static Banner + Reels",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 450,
        cpql: 1125,
        cpsv: 7875,
        cpb: 157500
    },

    // ---------- SHOWROOM ----------
    {
        segment: "Commercial",
        location: "East Ahmedabad",
        propertyType: "Showroom",
        adType: "Static Banner",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1400,
        cpql: 4278,
        cpsv: 19250,
        cpb: 385000
    },
    {
        segment: "Commercial",
        location: "East Ahmedabad",
        propertyType: "Showroom",
        adType: "Static Banner + Reels",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1250,
        cpql: 3820,
        cpsv: 17188,
        cpb: 343750
    },
    // ---------- OFFICE ----------
    {
        segment: "Commercial",
        location: "Central Ahmedabad",
        propertyType: "Office",
        adType: "Static Banner",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 250,
        cpql: 625,
        cpsv: 5000,
        cpb: 125000
    },
    {
        segment: "Commercial",
        location: "Central Ahmedabad",
        propertyType: "Office",
        adType: "Static Banner + Reels",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 200,
        cpql: 500,
        cpsv: 4000,
        cpb: 100000
    },

    // ---------- SHOP ----------
    {
        segment: "Commercial",
        location: "Central Ahmedabad",
        propertyType: "Shop",
        adType: "Static Banner",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1250,
        cpsv: 8750,
        cpb: 175000
    },
    {
        segment: "Commercial",
        location: "Central Ahmedabad",
        propertyType: "Shop",
        adType: "Static Banner + Reels",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 450,
        cpql: 1125,
        cpsv: 7875,
        cpb: 157500
    },

    // ---------- SHOWROOM ----------
    {
        segment: "Commercial",
        location: "Central Ahmedabad",
        propertyType: "Showroom",
        adType: "Static Banner",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1400,
        cpql: 4278,
        cpsv: 19250,
        cpb: 385000
    },
    {
        segment: "Commercial",
        location: "Central Ahmedabad",
        propertyType: "Showroom",
        adType: "Static Banner + Reels",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1250,
        cpql: 3820,
        cpsv: 17188,
        cpb: 343750
    },
    // ---------- OFFICE ----------
    {
        segment: "Commercial",
        location: "Gandhinagar",
        propertyType: "Office",
        adType: "Static Banner",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 250,
        cpql: 625,
        cpsv: 5000,
        cpb: 125000
    },
    {
        segment: "Commercial",
        location: "Gandhinagar",
        propertyType: "Office",
        adType: "Static Banner + Reels",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 200,
        cpql: 500,
        cpsv: 4000,
        cpb: 100000
    },

    // ---------- SHOP ----------
    {
        segment: "Commercial",
        location: "Gandhinagar",
        propertyType: "Shop",
        adType: "Static Banner",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1250,
        cpsv: 8750,
        cpb: 175000
    },
    {
        segment: "Commercial",
        location: "Gandhinagar",
        propertyType: "Shop",
        adType: "Static Banner + Reels",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 450,
        cpql: 1125,
        cpsv: 7875,
        cpb: 157500
    },

    // ---------- SHOWROOM ----------
    {
        segment: "Commercial",
        location: "Gandhinagar",
        propertyType: "Showroom",
        adType: "Static Banner",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1400,
        cpql: 4278,
        cpsv: 19250,
        cpb: 385000
    },
    {
        segment: "Commercial",
        location: "Gandhinagar",
        propertyType: "Showroom",
        adType: "Static Banner + Reels",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1250,
        cpql: 3820,
        cpsv: 17188,
        cpb: 343750
    },
    // ---------- OFFICE ----------
    {
        segment: "Commercial",
        location: "West Vadodara",
        propertyType: "Office",
        adType: "Static Banner",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 250,
        cpql: 625,
        cpsv: 5000,
        cpb: 125000
    },
    {
        segment: "Commercial",
        location: "West Vadodara",
        propertyType: "Office",
        adType: "Static Banner + Reels",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 200,
        cpql: 500,
        cpsv: 4000,
        cpb: 100000
    },

    // ---------- SHOP ----------
    {
        segment: "Commercial",
        location: "West Vadodara",
        propertyType: "Shop",
        adType: "Static Banner",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1250,
        cpsv: 8750,
        cpb: 175000
    },
    {
        segment: "Commercial",
        location: "West Vadodara",
        propertyType: "Shop",
        adType: "Static Banner + Reels",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 450,
        cpql: 1125,
        cpsv: 7875,
        cpb: 157500
    },

    // ---------- SHOWROOM ----------
    {
        segment: "Commercial",
        location: "West Vadodara",
        propertyType: "Showroom",
        adType: "Static Banner",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1400,
        cpql: 4278,
        cpsv: 19250,
        cpb: 385000
    },
    {
        segment: "Commercial",
        location: "West Vadodara",
        propertyType: "Showroom",
        adType: "Static Banner + Reels",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1250,
        cpql: 3820,
        cpsv: 17188,
        cpb: 343750
    },
    // ---------- OFFICE ----------
    {
        segment: "Commercial",
        location: "East Vadodara",
        propertyType: "Office",
        adType: "Static Banner",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 250,
        cpql: 625,
        cpsv: 5000,
        cpb: 125000
    },
    {
        segment: "Commercial",
        location: "East Vadodara",
        propertyType: "Office",
        adType: "Static Banner + Reels",
        baseLeads: 500,
        baseQL: 200,
        baseSV: 25,
        baseBookings: 1,
        cpl: 200,
        cpql: 500,
        cpsv: 4000,
        cpb: 100000
    },

    // ---------- SHOP ----------
    {
        segment: "Commercial",
        location: "East Vadodara",
        propertyType: "Shop",
        adType: "Static Banner",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1250,
        cpsv: 8750,
        cpb: 175000
    },
    {
        segment: "Commercial",
        location: "East Vadodara",
        propertyType: "Shop",
        adType: "Static Banner + Reels",
        baseLeads: 350,
        baseQL: 140,
        baseSV: 20,
        baseBookings: 1,
        cpl: 450,
        cpql: 1125,
        cpsv: 7875,
        cpb: 157500
    },

    // ---------- SHOWROOM ----------
    {
        segment: "Commercial",
        location: "East Vadodara",
        propertyType: "Showroom",
        adType: "Static Banner",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1400,
        cpql: 4278,
        cpsv: 19250,
        cpb: 385000
    },
    {
        segment: "Commercial",
        location: "East Vadodara",
        propertyType: "Showroom",
        adType: "Static Banner + Reels",
        baseLeads: 275,
        baseQL: 90,
        baseSV: 20,
        baseBookings: 1,
        cpl: 1250,
        cpql: 3820,
        cpsv: 17188,
        cpb: 343750
    },
    // ================= WEST AHMEDABAD =================

    // 3 BHK
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1000,
        cpsv: 5000,
        cpb: 100000,
    },
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 400,
        cpql: 800,
        cpsv: 4000,
        cpb: 80000,
    },

    // 4 BHK
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000,
    },
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000,
    },

    // 5 BHK
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 733,
        cpql: 3667,
        cpsv: 18333,
        cpb: 550000,
    },
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 667,
        cpql: 3333,
        cpsv: 16667,
        cpb: 500000,
    },

    // 6 BHK
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 1000,
        cpql: 5000,
        cpsv: 25000,
        cpb: 750000,
    },
    {
        segment: "Villa",
        location: "West Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000,
    },
    // ---------- 3 BHK ----------
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 400,
        cpql: 800,
        cpsv: 4000,
        cpb: 80000,
    },
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 300,
        cpql: 600,
        cpsv: 3000,
        cpb: 60000,
    },

    // ---------- 4 BHK ----------
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000,
    },
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 333,
        cpql: 1000,
        cpsv: 3333,
        cpb: 100000,
    },

    // ---------- 5 BHK ----------
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 600,
        cpql: 3000,
        cpsv: 15000,
        cpb: 450000,
    },
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 533,
        cpql: 2667,
        cpsv: 13333,
        cpb: 400000,
    },

    // ---------- 6 BHK ----------
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 733,
        cpql: 3667,
        cpsv: 18333,
        cpb: 550000,
    },
    {
        segment: "Villa",
        location: "East Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 666,
        cpql: 3333,
        cpsv: 16667,
        cpb: 500000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1000,
        cpsv: 5000,
        cpb: 100000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 400,
        cpql: 800,
        cpsv: 4000,
        cpb: 80000,
    },

    /* 4 BHK */
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000,
    },

    /* 5 BHK */
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 733,
        cpql: 3667,
        cpsv: 18333,
        cpb: 550000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 667,
        cpql: 3333,
        cpsv: 16667,
        cpb: 500000,
    },

    /* 6 BHK */
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 1000,
        cpql: 5000,
        cpsv: 25000,
        cpb: 750000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000,
    },
    // ✅ SEGMENT: VILLA — LOCATION: GANDHINAGAR

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1000,
        cpsv: 5000,
        cpb: 100000
    },

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 400,
        cpql: 800,
        cpsv: 4000,
        cpb: 80000
    },

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000
    },

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000
    },

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 733,
        cpql: 3667,
        cpsv: 18333,
        cpb: 550000
    },

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 667,
        cpql: 3333,
        cpsv: 16667,
        cpb: 500000
    },

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "6 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 1000,
        cpql: 5000,
        cpsv: 25000,
        cpb: 750000
    },

    {
        segment: "Villa",
        location: "Gandhinagar",
        propertyType: "6 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 500,
        cpql: 1000,
        cpsv: 5000,
        cpb: 100000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 400,
        cpql: 800,
        cpsv: 4000,
        cpb: 80000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 500,
        cpql: 1500,
        cpsv: 5000,
        cpb: 150000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 733,
        cpql: 3667,
        cpsv: 18333,
        cpb: 550000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 667,
        cpql: 3333,
        cpsv: 16667,
        cpb: 500000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 1000,
        cpql: 5000,
        cpsv: 25000,
        cpb: 750000,
    },
    {
        segment: "Villa",
        location: "Central Ahmedabad",
        propertyType: "6 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 800,
        cpql: 4000,
        cpsv: 20000,
        cpb: 600000,
    },
    // ✅ EAST VADODARA - VILLA

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "3 BHK",
        adType: "Static Banner",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 400,
        cpql: 800,
        cpsv: 4000,
        cpb: 80000,
    },

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "3 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 200,
        baseQL: 100,
        baseSV: 20,
        baseBookings: 1,
        cpl: 300,
        cpql: 600,
        cpsv: 3000,
        cpb: 60000,
    },

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "4 BHK",
        adType: "Static Banner",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 400,
        cpql: 1200,
        cpsv: 4000,
        cpb: 120000,
    },

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "4 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 300,
        baseQL: 100,
        baseSV: 30,
        baseBookings: 1,
        cpl: 333,
        cpql: 1000,
        cpsv: 3333,
        cpb: 100000,
    },

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "5 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 600,
        cpql: 3000,
        cpsv: 15000,
        cpb: 450000,
    },

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "5 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 533,
        cpql: 2667,
        cpsv: 13333,
        cpb: 400000,
    },

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "6 BHK",
        adType: "Static Banner",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 733,
        cpql: 3667,
        cpsv: 18333,
        cpb: 550000,
    },

    {
        segment: "Villa",
        location: "East Vadodara",
        propertyType: "6 BHK",
        adType: "Static Banner + Reels",
        baseLeads: 750,
        baseQL: 150,
        baseSV: 30,
        baseBookings: 1,
        cpl: 666,
        cpql: 3333,
        cpsv: 16667,
        cpb: 500000,
    }

];
