const OurWorkGridData = [
    {
        category: "Drone Shoots",
        works: [
            {
                title: "The One — Signature Aerial Story",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "The One Signature Aerial Story drone video thumbnail showcasing real estate project aerial view by The Bliss Solution",
                description: "A cinematic flythrough for The One, revealing the full vertical drama and skyline integration.",
                videoUrl: "https://youtu.be/nKTIqJxweME",
                type: "video",
            },
            {
                title: "Satatya — Precision Flight Narrative",
                image: "/Images/HordingImages/Hoarding2.png",
                alt: "Satatya Precision Flight Narrative drone video thumbnail featuring real estate project aerial cinematography by The Bliss Solution",
                description: "High-energy drone choreography that showcases Satatya's geometric massing and urban context.",
                videoUrl: "https://www.youtube.com/watch?v=KkBWg1W2LSY&feature=youtu.be",
                type: "video",
            },
            {
                title: "Zade 2 — Immersive Site Journey",
                image: "/Images/HordingImages/Hoarding3.png",
                alt: "Zade 2 Immersive Site Journey drone video thumbnail displaying real estate project landscape and architecture by The Bliss Solution",
                description: "A sweeping aerial reveal that captures Zade 2's scale, landscape integration, and lifestyle promise.",
                videoUrl: "https://youtu.be/rdAlVNdrsek",
                type: "video",
            },
            {
                title: "Times Trinity — Vertical Experience Film",
                image: "/Images/HordingImages/Hoarding2.jpg",
                alt: "Times Trinity Vertical Experience Film drone video thumbnail showing real estate tower architecture and prime location by The Bliss Solution",
                description: "Right-to-left drone passes that highlight the tower's architectural rhythm and prime location.",
                videoUrl: "https://youtu.be/0_ukl6VAX-A",
                type: "video",
            },
            {
                title: "Yash Terranova — Immersive Skyline Story",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "Yash Terranova Immersive Skyline Story drone video thumbnail featuring real estate project architecture and city context by The Bliss Solution",
                description: "A multi-angle drone narrative that stitches together Terranova's architecture, amenity decks, and city context.",
                videoUrl: "https://youtu.be/NiDeTaderHY",
                type: "video",
            },
            {
                title: "TIMES 104 — Launch Flythrough",
                image: "/Images/HordingImages/Hoarding3.png",
                alt: "TIMES 104 Launch Flythrough drone video thumbnail showcasing real estate project urban grid and scale by The Bliss Solution",
                description: "A bold aerial sequence that captures the urban grid, scale, and momentum of Times 104's debut.",
                videoUrl: "https://youtu.be/V5eXq95VeXA",
                type: "video",
            },
        ],
    },
    {
        category: "CGI videos",
        works: [
            {
                title: "Shreeji_Sarvtra",
                videoUrl: "https://res.cloudinary.com/dpjtupftc/video/upload/v1764326195/Shreeji_Sarvtra_CGI_V1_1_stf4qb.mp4",
                image: "/Images/HordingImages/Ho arding1.jpg",
                alt: "Shreeji Sarvtra CGI video thumbnail featuring township launch narrative and real estate project visualization by The Bliss Solution",
                description: "Sweeping drone passes capture the full scale of the township launch narrative.",
                type: "video",
            },
            {
                title: "THE_METRO_PARK",
                videoUrl: "https://res.cloudinary.com/dpjtupftc/video/upload/v1764326200/THE_METRO_PARK_CGI_01_1_sow54g.mp4",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "THE METRO PARK CGI video thumbnail showcasing real estate project computer-generated imagery and marketing video by The Bliss Solution",
                description: "Sweeping drone passes capture the full scale of the township launch narrative.",
                type: "video",
            },
            {
                title: "Vedant_calisto",
                videoUrl: "https://res.cloudinary.com/dpjtupftc/video/upload/v1764326201/Vedant_calisto_CGI_1_iyakbr.mp4",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "Vedant Calisto CGI video thumbnail displaying real estate project 3D visualization and marketing content by The Bliss Solution",
                description: "Sweeping drone passes capture the full scale of the township launch narrative.",
                type: "video",
            },
            {
                title: "Zade_Group_Diwali",
                videoUrl: "https://res.cloudinary.com/dpjtupftc/video/upload/v1764326201/Zade_Group_Diwali_CGI_1_pvfcry.mp4",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "Zade Group Diwali CGI video thumbnail featuring festive real estate project marketing video and 3D animation by The Bliss Solution",
                description: "Sweeping drone passes capture the full scale of the township launch narrative.",
                type: "video",
            },
            {
                title: "Samved_Statley",
                videoUrl: "https://res.cloudinary.com/dpjtupftc/video/upload/v1764326203/Samved_Statley_CGI_V1_1_uyrqv0.mp4",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "Samved Statley CGI video thumbnail showcasing real estate project computer-generated imagery and promotional video by The Bliss Solution",
                description: "Sweeping drone passes capture the full scale of the township launch narrative.",
                type: "video",
            },
            {
                title: "Times Trinity",
                videoUrl: "https://res.cloudinary.com/dpjtupftc/video/upload/v1764326201/TIMES_TRINITY_CGI-V1_1_glhmrz.mp4",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "Times Trinity CGI video thumbnail displaying real estate project 3D visualization and marketing content by The Bliss Solution",
                description: "Sweeping drone passes capture the full scale of the township launch narrative.",
                type: "video",
            },
            {
                title: "Vedant Skyway",
                videoUrl: "https://res.cloudinary.com/dpjtupftc/video/upload/v1764326207/VEDANT_SKYWAY_CGI_1_zryq9x.mp4 ",
                image: "/Images/HordingImages/Hoarding1.jpeg",
                alt: "Vedant Skyway CGI video thumbnail featuring real estate project computer-generated imagery and promotional video by The Bliss Solution",
                description: "Sweeping drone passes capture the full scale of the township launch narrative.",
                type: "video",
            },
        ],
    },
    {
        category: "Brochures",
        works: [
            {
                title: "Skyline Rera",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/SkylinRera.pdf",
                image: "/Images/CoverPagesImages/skyline.jpg",
                alt: "Skyline Rera premium residential project brochure cover page showcasing luxury living spaces and amenities by The Bliss Solution",
                description: "Premium residential project brochure showcasing luxury living spaces and amenities.",
                type: "pdf",
            },
            {
                title: "Tatva Bliss",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/TatvaBlissBrochure.pdf",
                image: "/Images/CoverPagesImages/tatva-bliss.jpg",
                alt: "Tatva Bliss elite township project brochure cover page highlighting modern architecture and lifestyle by The Bliss Solution",
                description: "Elite township project brochure highlighting modern architecture and lifestyle.",
                type: "pdf",
            },
            {
                title: "Shyam Developer",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/ShyamDeveloperBrochure.pdf",
                image: "/Images/CoverPagesImages/shyam-devloper.jpg",
                alt: "Shyam Developer comprehensive portfolio brochure cover page showcasing multiple residential projects by The Bliss Solution",
                description: "Comprehensive developer portfolio showcasing multiple residential projects.",
                type: "pdf",
            },
            {
                title: "Shreemad",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/ShreemadBrochure.pdf",
                image: "/Images/PdfDocuments/Images/ShreemadBrochure.png",
                alt: "Shreemad luxury residential development brochure cover page featuring premium amenities and design by The Bliss Solution",
                description: "Luxury residential development brochure featuring premium amenities and design.",
                type: "pdf",
            },
            {
                title: "Shreeji",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/SHREEJIBrocher.pdf",
                image: "/Images/PdfDocuments/Images/SHREEJIBrocher.png",
                alt: "Shreeji premium real estate project brochure cover page with detailed floor plans and amenities by The Bliss Solution",
                description: "Premium real estate project brochure with detailed floor plans and amenities.",
                type: "pdf",
            },
            {
                title: "Keshvaa Pre Rera",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/KeshvaaPreReraBrochure.pdf",
                image: "/Images/CoverPagesImages/keshav-narayan.jpg",
                alt: "Keshvaa Pre Rera project documentation and marketing brochure cover page by The Bliss Solution",
                description: "Pre-RERA project documentation and marketing brochure.",
                type: "pdf",
            },
            {
                title: "Inara",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/InaraBrochure.pdf",
                image: "/Images/PdfDocuments/Images/InaraBrochure.png",
                alt: "Inara luxury residential project brochure cover page showcasing premium living experience by The Bliss Solution",
                description: "Luxury residential project brochure showcasing premium living experience.",
                type: "pdf",
            },
            {
                title: "Vertex Jade",
                pdfUrl: "https://s3.ap-south-1.amazonaws.com/prepseed/prod/ldoc/media/VertexJadeBroucher.pdf",
                image: "/Images/CoverPagesImages/jade-group.jpg",
                alt: "Vertex Jade premium commercial and residential development brochure cover page by The Bliss Solution",
                description: "Premium commercial and residential development brochure.",
                type: "pdf",
            },
        ],
    },

];

export default OurWorkGridData;
